"use strict";
exports.__esModule = true;
exports.useRg = exports.useResedentialPhone = exports.useMobilePhone = exports.useCep = exports.useCpf = exports.useMoney = void 0;
var useFormat_1 = require("./useFormat");
exports.useMoney = useFormat_1.useMoney;
exports.useCpf = useFormat_1.useCpf;
exports.useCep = useFormat_1.useCep;
exports.useMobilePhone = useFormat_1.useMobilePhone;
exports.useResedentialPhone = useFormat_1.useResedentialPhone;
exports.useRg = useFormat_1.useRg;
